### PR TITLE
Styling for all authentication related pages

### PR DESCRIPTION
**Pull request by safchow**
## Trello ticket link

[Developer Task: Implement UI/UX feedback to authentication pages](https://trello.com/c/Pgeu6734/127-developer-task-implement-ui-ux-feedback-to-authentication-pages )

## Implementation description
* Add styling for all authentication pages. This includes:
    1. Forgot Password
    2. Log In
    3. Sign Up
    4. Update Credentials
    5. Update Status
    6. User Settings
    

## Steps to test
1. Please verify that all functionality from the updated pages still work the same. This includes:
    1. Being able to create a new account (use a gmail account to test forget password)
    2. Being able to log in
    3. Being able to update your credentials
    4. Being able to update your status (also double check the page is correctly styled when archived, and when active)
    5. Routing to and from user settings works (from update status page, and update credentials page)
    6. Password reset: use a non-waterloo account to verify you get the password reset email

### CODE REVIEW

**Review by gabbytang — APPROVED** [review]
All functionality works as expected. Styling looks great! Only thing I noticed is that you can't login by clicking the "Enter" button on your keyboard, you need to click the login button. Not that big of a deal though

**Review by Eshah7 — CHANGES_REQUESTED** [review]
Can we add "New Password" instead of "Password"?
Screenshot 2023-03-22 at 10 24 10 AM

**Comment by Eshah7** [comment]
Screenshot 2023-03-22 at 10 28 47 AM

Not sure why, but when I try to update my password, it doesn't seem to work. Are there requirements on what your new password should be like? 

**Update: Works when I logged out and logged back in!**

**Comment by Eshah7** [comment]
image

It mentioned that I failed to create an account, however, I was able to log into it!

Edit: My email or my name isn't stored in the database. However, here is proof I can log in: 
Screenshot 2023-03-22 at 10 34 23 AM

Also, I can change my password successfully (got the email and everything), but I still do not see my email in our user's database... If there is a password length minimum requirement, I would suggest adding that too, thanks!

**Comment by Eshah7** [comment]
I would suggest adding a little toast message saying that the user should check their email when they reset their password: 
Screenshot 2023-03-22 at 10 38 00 AM

**Comment by safchow** [comment]
> All functionality works as expected. Styling looks great! Only thing I noticed is that you can't login by clicking the "Enter" button on your keyboard, you need to click the login button. Not that big of a deal though

all of our text inputs on the app are unfortunately like that :( it would take time to refactor all of it so I'd rather not make the change only on the log in page and have the rest of the app not have that feature

**Comment by safchow** [comment]
> image
> 
> It mentioned that I failed to create an account, however, I was able to log into it!
> 
> Edit: My email or my name isn't stored in the database. However, here is proof I can log in: Screenshot 2023-03-22 at 10 34 23 AM
> 
> Also, I can change my password successfully (got the email and everything), but I still do not see my email in our user's database... If there is a password length minimum requirement, I would suggest adding that too, thanks!

@Eshah7 I wasn't able to replicate this issue. In my testing, I was able to sign up and was redirected to the landing page. A new user row was added to our db. If you can replicate this issue, can you post the steps taken to do so?

**Comment by Eshah7** [comment]
> > image
> > It mentioned that I failed to create an account, however, I was able to log into it!
> > Edit: My email or my name isn't stored in the database. However, here is proof I can log in: Screenshot 2023-03-22 at 10 34 23 AM
> > Also, I can change my password successfully (got the email and everything), but I still do not see my email in our user's database... If there is a password length minimum requirement, I would suggest adding that too, thanks!
> 
> @Eshah7 I wasn't able to replicate this issue. In my testing, I was able to sign up and was redirected to the landing page. A new user row was added to our db. If you can replicate this issue, can you post the steps taken to do so?

I was unable to replicate it as well... not sure where things went wrong - but redid the steps and everything looks good! Thanks :)

**Review by Eshah7 — APPROVED** [review]
LGTM!

**Pull request merged**
