### PR TITLE
Styling for Forum and My Comments Page

### PR DESCRIPTION
**Pull request by safchow**
## Trello ticket link

[Developer Task: Styling for Forum page](https://trello.com/c/DqWNt0Op/137-developer-task-styling-for-forum-page)
[Developer Task: Styling for My Comments page](https://trello.com/c/GL1td3b6/138-developer-task-styling-for-my-comments-page)

## Implementation description
* Styled Forum page, and all dialogues
* Added My Comments to nav bar
* Styled My Comments page

## Steps to test
Forum Page:
1. Verify all dialogue options are working
2. Verify there are no styling inconsistencies
3. Verify correct toast messages appear for each case (successful submission, bad submission, etc.)

My Comments Page:
1. Verify page is accessible through nav bar
2. Verify there are no styling inconsistencies
3. Verify links take you to the correct forum
4. Verify you cannot create an empty comment
5. Verify you cannot edit a comment to be an empty string

## What should reviewers focus on?
*

### CODE REVIEW

**Review by c45choi — APPROVED** [review]
LGTM

**Review by Eshah7 — CHANGES_REQUESTED** [review]
Screenshot 2023-03-26 at 1 11 21 AM

Probs change "name" to "comment"?

**Review by Eshah7 — COMMENTED** [review]
Oh god... daylight savings time probs issue: 
Screenshot 2023-03-26 at 1 12 01 AM

I can update it later in a hotfix - we are probably experiencing this issue on everything!

**Review by c45choi — CHANGES_REQUESTED** [review]
for some reason i just submitted an empty string and i got success
Screenshot 2023-03-26 at 1 13 29 AM
 and it shows up empty in my comments

**Comment by safchow** [comment]
> for some reason i just submitted an empty string and i got success Screenshot 2023-03-26 at 1 13 29 AM and it shows up empty in my comments

I'm unable to re-create this error, this is what I see:
image

Can you pull latest and try again? If it occurs, can you write down the steps to re-create?

**Review by Eshah7 — APPROVED** [review]
lgtm!!

**Review by c45choi — APPROVED** [review]
weird ,, it works now? 
Screenshot 2023-03-26 at 9 49 39 AM

those were from before so idk. ill just approve for now cause ti works now

**Pull request merged**
