### PR TITLE
Implemented search function in forums and resources

### PR DESCRIPTION
**Pull request by gabbytang**
## Trello ticket link

[As a user, I can search for forums so that I can find relevant topics.](https://trello.com/c/K5XlVZev )
[As a user, I can search for resources so that I can find relevant resources.](https://trello.com/c/gMZmEUcw)

## Implementation description
* Added search functionality to Forums, My Forums, and Resources page
* For the Forum page, users can search by forum title, description, and creator name 
* For the My Forums page, users can search by forum title and description
* For the Resouces page, users can search by resource title and creator name
* Updated styling for search bar, search button, and clear search
* Added Clear Search functionality to the Search.js file

## Steps to test
1. If you have not already installed the new styling components, run `npm i`
2. Go to each of the pages: Forums, My Forums, and Resources
3. Ensure that when the page renders, the entire list of forums/resources is there
4. Test that you can type any string into the text box
5. Clicking the magnifying glass icon should run the search and the list of items that match your search should be rendered
6. Check that the returned list matches your search term 
7. If the search bar is empty, the page should return the entire list of items  in the db 
8. Clicking the "Clear Search" should reset the search bar and render the list of all items in the db

## What should reviewers focus on?
* Check the styling is consistent
* Ensure that the search function works as expected

### CODE REVIEW

**Review by c45choi — CHANGES_REQUESTED** [review]
for resources, i cant search based on link - is that expected?

**Review by c45choi — CHANGES_REQUESTED** [review]
i was wondering, would it be possible to have a little blurb on what could be searched for? i noticed for forums, status cant be searched either or for resources, links

perhaps we can do a little text under the text box

**Review by c45choi — APPROVED** [review]

**Comment by safchow** [comment]
> for resources, i cant search based on link - is that expected?

not sure if we want this as part of the search, users are ideally searching by name and not for a specific link maybe @gabbytang can comment

**Comment by safchow** [comment]
> i was wondering, would it be possible to have a little blurb on what could be searched for? i noticed for forums, status cant be searched either or for resources, links
> 
> perhaps we can do a little text under the text box

I agree, this would be helpful to have

**Review by safchow — CHANGES_REQUESTED** [review]
everything works perfectly, I would look into adding some text under each of the searches as to what the search uses as a filter

**Comment by gabbytang** [comment]
> > for resources, i cant search based on link - is that expected?
> 
> not sure if we want this as part of the search, users are ideally searching by name and not for a specific link maybe @gabbytang can comment

Yeah I think it makes more sense to just search by resource name. I don't think its intuitive for someone to search for a URL link

**Review by safchow — CHANGES_REQUESTED** [review]
you need to update the label for resources as well

**Review by safchow — APPROVED** [review]

**Pull request merged**
